//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021 The cert-manager Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "github.com/jetstack/cert-manager/pkg/apis/certmanager/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateRequestPolicy) DeepCopyInto(out *CertificateRequestPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateRequestPolicy.
func (in *CertificateRequestPolicy) DeepCopy() *CertificateRequestPolicy {
	if in == nil {
		return nil
	}
	out := new(CertificateRequestPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CertificateRequestPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateRequestPolicyIssuerRefSelector) DeepCopyInto(out *CertificateRequestPolicyIssuerRefSelector) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Kind != nil {
		in, out := &in.Kind, &out.Kind
		*out = new(string)
		**out = **in
	}
	if in.Group != nil {
		in, out := &in.Group, &out.Group
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateRequestPolicyIssuerRefSelector.
func (in *CertificateRequestPolicyIssuerRefSelector) DeepCopy() *CertificateRequestPolicyIssuerRefSelector {
	if in == nil {
		return nil
	}
	out := new(CertificateRequestPolicyIssuerRefSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateRequestPolicyIssuerRefSelector) DeepCopyInto(out *CertificateRequestPolicyIssuerRefSelector) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Kind != nil {
		in, out := &in.Kind, &out.Kind
		*out = new(string)
		**out = **in
	}
	if in.Group != nil {
		in, out := &in.Group, &out.Group
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateRequestPolicyIssuerRefSelector.
func (in *CertificateRequestPolicyIssuerRefSelector) DeepCopy() *CertificateRequestPolicyIssuerRefSelector {
	if in == nil {
		return nil
	}
	out := new(CertificateRequestPolicyIssuerRefSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateRequestPolicyList) DeepCopyInto(out *CertificateRequestPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CertificateRequestPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateRequestPolicyList.
func (in *CertificateRequestPolicyList) DeepCopy() *CertificateRequestPolicyList {
	if in == nil {
		return nil
	}
	out := new(CertificateRequestPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CertificateRequestPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateRequestPolicyPluginData) DeepCopyInto(out *CertificateRequestPolicyPluginData) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateRequestPolicyPluginData.
func (in *CertificateRequestPolicyPluginData) DeepCopy() *CertificateRequestPolicyPluginData {
	if in == nil {
		return nil
	}
	out := new(CertificateRequestPolicyPluginData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateRequestPolicyPrivateKey) DeepCopyInto(out *CertificateRequestPolicyPrivateKey) {
	*out = *in
	if in.AllowedAlgorithm != nil {
		in, out := &in.AllowedAlgorithm, &out.AllowedAlgorithm
		*out = new(v1.PrivateKeyAlgorithm)
		**out = **in
	}
	if in.MinSize != nil {
		in, out := &in.MinSize, &out.MinSize
		*out = new(int)
		**out = **in
	}
	if in.MaxSize != nil {
		in, out := &in.MaxSize, &out.MaxSize
		*out = new(int)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateRequestPolicyPrivateKey.
func (in *CertificateRequestPolicyPrivateKey) DeepCopy() *CertificateRequestPolicyPrivateKey {
	if in == nil {
		return nil
	}
	out := new(CertificateRequestPolicyPrivateKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateRequestPolicySpec) DeepCopyInto(out *CertificateRequestPolicySpec) {
	*out = *in
	if in.AllowedSubject != nil {
		in, out := &in.AllowedSubject, &out.AllowedSubject
		*out = new(CertificateRequestPolicyX509Subject)
		(*in).DeepCopyInto(*out)
	}
	if in.AllowedCommonName != nil {
		in, out := &in.AllowedCommonName, &out.AllowedCommonName
		*out = new(string)
		**out = **in
	}
	if in.MinDuration != nil {
		in, out := &in.MinDuration, &out.MinDuration
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.MaxDuration != nil {
		in, out := &in.MaxDuration, &out.MaxDuration
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.AllowedDNSNames != nil {
		in, out := &in.AllowedDNSNames, &out.AllowedDNSNames
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.AllowedIPAddresses != nil {
		in, out := &in.AllowedIPAddresses, &out.AllowedIPAddresses
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.AllowedURIs != nil {
		in, out := &in.AllowedURIs, &out.AllowedURIs
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.AllowedEmailAddresses != nil {
		in, out := &in.AllowedEmailAddresses, &out.AllowedEmailAddresses
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.AllowedIsCA != nil {
		in, out := &in.AllowedIsCA, &out.AllowedIsCA
		*out = new(bool)
		**out = **in
	}
	if in.AllowedUsages != nil {
		in, out := &in.AllowedUsages, &out.AllowedUsages
		*out = new([]v1.KeyUsage)
		if **in != nil {
			in, out := *in, *out
			*out = make([]v1.KeyUsage, len(*in))
			copy(*out, *in)
		}
	}
	if in.AllowedPrivateKey != nil {
		in, out := &in.AllowedPrivateKey, &out.AllowedPrivateKey
		*out = new(CertificateRequestPolicyPrivateKey)
		(*in).DeepCopyInto(*out)
	}
	if in.Plugins != nil {
		in, out := &in.Plugins, &out.Plugins
		*out = make(map[string]CertificateRequestPolicyPluginData, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.IssuerRefSelector != nil {
		in, out := &in.IssuerRefSelector, &out.IssuerRefSelector
		*out = new(CertificateRequestPolicyIssuerRefSelector)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateRequestPolicySpec.
func (in *CertificateRequestPolicySpec) DeepCopy() *CertificateRequestPolicySpec {
	if in == nil {
		return nil
	}
	out := new(CertificateRequestPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateRequestPolicyStatus) DeepCopyInto(out *CertificateRequestPolicyStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateRequestPolicyStatus.
func (in *CertificateRequestPolicyStatus) DeepCopy() *CertificateRequestPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(CertificateRequestPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateRequestPolicyX509Subject) DeepCopyInto(out *CertificateRequestPolicyX509Subject) {
	*out = *in
	if in.AllowedOrganizations != nil {
		in, out := &in.AllowedOrganizations, &out.AllowedOrganizations
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.AllowedCountries != nil {
		in, out := &in.AllowedCountries, &out.AllowedCountries
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.AllowedOrganizationalUnits != nil {
		in, out := &in.AllowedOrganizationalUnits, &out.AllowedOrganizationalUnits
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.AllowedLocalities != nil {
		in, out := &in.AllowedLocalities, &out.AllowedLocalities
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.AllowedProvinces != nil {
		in, out := &in.AllowedProvinces, &out.AllowedProvinces
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.AllowedStreetAddresses != nil {
		in, out := &in.AllowedStreetAddresses, &out.AllowedStreetAddresses
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.AllowedPostalCodes != nil {
		in, out := &in.AllowedPostalCodes, &out.AllowedPostalCodes
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.AllowedSerialNumber != nil {
		in, out := &in.AllowedSerialNumber, &out.AllowedSerialNumber
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateRequestPolicyX509Subject.
func (in *CertificateRequestPolicyX509Subject) DeepCopy() *CertificateRequestPolicyX509Subject {
	if in == nil {
		return nil
	}
	out := new(CertificateRequestPolicyX509Subject)
	in.DeepCopyInto(out)
	return out
}
