// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0
// source: pkg/internal/approver/validation/certificaterequest.proto

package validation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CertificateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertificateRequest) Reset() {
	*x = CertificateRequest{}
	mi := &file_pkg_internal_approver_validation_certificaterequest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateRequest) ProtoMessage() {}

func (x *CertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_internal_approver_validation_certificaterequest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateRequest.ProtoReflect.Descriptor instead.
func (*CertificateRequest) Descriptor() ([]byte, []int) {
	return file_pkg_internal_approver_validation_certificaterequest_proto_rawDescGZIP(), []int{0}
}

func (x *CertificateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CertificateRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *CertificateRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

var File_pkg_internal_approver_validation_certificaterequest_proto protoreflect.FileDescriptor

const file_pkg_internal_approver_validation_certificaterequest_proto_rawDesc = "" +
	"\n" +
	"9pkg/internal/approver/validation/certificaterequest.proto\x12-cm.io.policy.pkg.internal.approver.validation\"b\n" +
	"\x12CertificateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busernameBJZHgithub.com/cert-manager/approver-policy/pkg/internal/approver/validationb\x06proto3"

var (
	file_pkg_internal_approver_validation_certificaterequest_proto_rawDescOnce sync.Once
	file_pkg_internal_approver_validation_certificaterequest_proto_rawDescData []byte
)

func file_pkg_internal_approver_validation_certificaterequest_proto_rawDescGZIP() []byte {
	file_pkg_internal_approver_validation_certificaterequest_proto_rawDescOnce.Do(func() {
		file_pkg_internal_approver_validation_certificaterequest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_internal_approver_validation_certificaterequest_proto_rawDesc), len(file_pkg_internal_approver_validation_certificaterequest_proto_rawDesc)))
	})
	return file_pkg_internal_approver_validation_certificaterequest_proto_rawDescData
}

var file_pkg_internal_approver_validation_certificaterequest_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_internal_approver_validation_certificaterequest_proto_goTypes = []any{
	(*CertificateRequest)(nil), // 0: cm.io.policy.pkg.internal.approver.validation.CertificateRequest
}
var file_pkg_internal_approver_validation_certificaterequest_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_internal_approver_validation_certificaterequest_proto_init() }
func file_pkg_internal_approver_validation_certificaterequest_proto_init() {
	if File_pkg_internal_approver_validation_certificaterequest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_internal_approver_validation_certificaterequest_proto_rawDesc), len(file_pkg_internal_approver_validation_certificaterequest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_internal_approver_validation_certificaterequest_proto_goTypes,
		DependencyIndexes: file_pkg_internal_approver_validation_certificaterequest_proto_depIdxs,
		MessageInfos:      file_pkg_internal_approver_validation_certificaterequest_proto_msgTypes,
	}.Build()
	File_pkg_internal_approver_validation_certificaterequest_proto = out.File
	file_pkg_internal_approver_validation_certificaterequest_proto_goTypes = nil
	file_pkg_internal_approver_validation_certificaterequest_proto_depIdxs = nil
}
