{{- if .Values.startupapicheck.enabled }}
{{- if .Values.startupapicheck.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: {{ .Values.startupapicheck.serviceAccount.automountServiceAccountToken }}
metadata:
  name: {{ include "startupapicheck.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  {{- with .Values.startupapicheck.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app: {{ include "startupapicheck.name" . }}
    {{- include "cert-manager-approver-policy.labels" . | nindent 4 }}
    app.kubernetes.io/component: startupapicheck
{{- end }}
{{- end }}
