{{ if .Values.app.usePoliciesRbac.enabled }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    {{- include "cert-manager-approver-policy.labels" . | nindent 4 }}
  name: {{ printf "%s:%s" (include "cert-manager-approver-policy.name" .) "use" }}
rules:
- apiGroups: ["policy.cert-manager.io"]
  resources: ["certificaterequestpolicies"]
  verbs: ["use"]
  {{- with .Values.app.usePoliciesRbac.policyNames }}
  resourceNames:
  {{- range . }}
  - "{{ . }}"
  {{- end  }}
  {{- end }}
{{ end }}
